apiVersion: v1
kind: Service
metadata:
  name: latency-gitlab
  labels:
    name: latency-gitlab
    app: exercise-gitlab

spec:
  selector:
    name: latency-gitlab
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
