apiVersion: v1
kind: ReplicationController
metadata:
  name: latency-gitlab
  labels:
    name: latency-gitlab
    app: exercise-gitlab

spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: latency-gitlab
    spec:
      containers:
        - name: latency-gitlab
          image: mujtaba1991/learngo
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
